language: ruby
gemfile:
  - test/support/Gemfile
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - bundle exec rake foodcritic
script:
    - bundle exec rake foodcritic
    - bundle exec rake knife
