# -*- encoding : utf-8 -*-
default[:coins][:bitcoin][:source] = 'https://github.com/bitcoin/bitcoin/archive/0.9.1.tar.gz'
default[:coins][:bitcoin][:executable] = 'bitcoind'
default[:coins][:bitcoin][:rpc_user] = 'bitcoin'
default[:coins][:bitcoin][:rpc_pass] = 'bitcoind'
default[:coins][:bitcoin][:rpc_port] = '8332'
default[:coins][:bitcoin][:rpc_allow_net] = '127.0.0.1'
default[:coins][:bitcoin][:wallet_location] = 'S3'
default[:coins][:bitcoin][:wallet_s3_bucket] = ''
default[:coins][:bitcoin][:wallet_s3_key] = ''
default[:coins][:bitcoin][:wallet_s3_secret] = ''
